In [2]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/holtzy/D3-graph-gallery/master/DATA/heatmap_data.csv"

data = pd.read_csv(url)
data

   group variable  value
0      A       v1     30
1      A       v2     95
2      A       v3     22
3      A       v4     14
4      A       v5     59
..   ...      ...    ...
95     J       v6     64
96     J       v7      4
97     J       v8     12
98     J       v9     97
99     J      v10     72

[100 rows x 3 columns]